#!/bin/sh
regex='@gmail\.com$'

email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then
	echo your email $email satisfies Git policy
	exit 0
else
	echo "your email $email does not satisfies Git policy"
	exit 1

fi